# Generated by Django 5.2.8 on 2025-11-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
